name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 触发部署的分支，可以根据需要修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 根据你的项目需求选择合适的 Node.js 版本

      # 步骤 3: 缓存依赖以加快构建速度
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 步骤 4: 安装依赖
      - name: Install dependencies
        run: npm ci

      # 步骤 5: 构建项目
      - name: Build project
        run: npm run build
        env:
          VITE_ENV: production # 根据需要设置环境变量

      # 步骤 6: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Vite 默认的输出目录是 dist，如果不同请修改
